.\" Manpage for hangman.
.\" Contact jrviner2000@gmail.com to correct errors or typos.
.TH man 1 "12 Nov 2022" "1.0" "ws man page"
.SH NAME
ws \- Sort words from stdin or file
.SH SYNOPSIS
Usage: ws [OPTION]... [FILE]...
.SH DESCRIPTION
Wordsorter (ws) sorts individual words out of a number of given files or from standard input. By default, the ws utility sorts by ASCII codepoint and in ascending order and prints the results to the standard output. The ws program considers a word to be a string of characters delimited by a white space character.
.SH OPTIONS
.TP
.BR -a ","
ASCII sort. This is the default for the program.
.TP
.BR -c " NUM,"
Indicates the number of n words to print from the top of the list of sorted words.
.TP
.BR -C " NUM,"
Indicates the count n of words to print from the bottom of the list of sorted words.
.TP
.BR -h ","
Prints a help message and exits.
.TP
.BR -i ","
Sorts case-insensitively.
.TP
.BR -l ","
Sorts by word length.
.TP
.BR -n ","
Sorts by numerical value.
.TP
.BR -r ","
Sorts in reverse order. May be passed multiple times, every two instances of -r cancel each other out.
.TP
.BR -s ","
Sorts using the Scrabble-scoring algorithm without removing invalid words.
.TP
.BR -S ","
Sorts using the Scrabble-scoring algorithm, removing words that cannot be formed by the base tile set (including blank tiles).
.TP
.BR -u ","
Prints only unique values.

